services:
  api:
    build:
      context: ./EduShelf.Api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./EduShelf.Api/Uploads:/app/Uploads

  web:
    build:
      context: ./edushelf-web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_TARGET=http://api:8080
    depends_on:
      - api